version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest

  pre_build:
    commands:
      # Enter directory
      - cd logon-lambda-api

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $COMMIT_HASH

      - echo Restore started on `date`
      - dotnet restore

  build:
    commands:
      - echo Build started on `date`
      - dotnet build

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o app --self-contained false src/BevCapital.Logon.API

      - FILE_NAME=ms-logon-lambda-$COMMIT_HASH.zip
      - echo $FILE_NAME

      - echo "Compressing the package.."
      - cd app
      - zip -r $FILE_NAME .
      - echo "Uploading to S3.."
      - aws s3 cp $FILE_NAME s3://${BUCKET_NAME}/$FILE_NAME
      - echo "Done."

      # Generate json with service name
      - cd ..
      - printf '{' >> service.json
      - printf ' "FileName":"%s" ' ${FILE_NAME} >> service.json
      - printf '}' >> service.json
artifacts:
  files:
    - ./logon-lambda-api/service.json
  discard-paths: yes
  # secondary-artifacts:
  #   appS3:
  #     files:
  #       - ./logon-lambda-api/app/*
  #     discard-paths: yes
  #     name: $FILE_NAME
