AWSTemplateFormatVersion: 2010-09-09
Description: Creates a pipeline and deploys a lambda service
Parameters:

  GitHubRepositoryOwner:
    Type: String
    Default: esilean
    Description: >
      Owner of the GitHub Repository containing the CloudFormation template being deployed. Usually
      your GitHub username

  GitHubRepositoryName:
    Type: String
    Default: bevcapital-mslogon
    Description: >
      Name of the GitHub repository containing the CloudFormation template being deployed. For this
      example, most likely would be "aws-cloudformation-pipeline-example" but might be different if
      you changed the name of the forked repository

  GitHubIntegrationBranch:
    Type: String
    Default: main
    Description: >
      Git branch on which integration occurs. Typical value here would be "master" but might differ
      for your specific use case

  DeploymentStackName:
    Type: String
    Default: MSLogonLambda
    Description: >
      Name to give the production stack that is deployed as part of the pipeline

  RepositoryName:
    Description: The repository name of the service
    Type: String
    MinLength: "2"
    MaxLength: "256"
    Default: bevcapital-mslogon
    AllowedPattern: "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*"

  GitHubPersonalAccessToken:
    Type: String
    Default: ""
    NoEcho: true
    Description: >
      Personal Access Token from GitHub that is used by CodePipeline to clone the source from the
      repository and configure webhooks. This personal access token requires the "repo" and
      "admin:repo_hook" scopes in order to function correctly. It is strongly recommended that this
      value be provided using Secrets Manager. In order to pass value from Secrets Manager, set this
      parameter value to "{{resolve:secretsmanager:your-secret-id:SecretString}}". More information
      see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html

  PassGitHubPersonalAccessTokenToCodeBuild:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Description: >
      Determines whether or not your personal access token is passed to CodeBuild. Set this value to
      "true" if this is the first time using CodeBuild with GitHub, as CodeBuild only supports one
      personal access token per account, per region. If you have already configured other CodeBuild
      projects to integrate with GitHub previously, set this value to "false".

Conditions:
  CreateCodeBuildCredentials:
    !Equals [!Sub "${PassGitHubPersonalAccessTokenToCodeBuild}", "true"]

Resources:

  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ms-logon-lambda
      AccessControl: LogDeliveryWrite
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - ServerSideEncryptionByDefault:
      #         SSEAlgorithm: aws:kms
      #         KMSMasterKeyID: alias/aws/s3
      LoggingConfiguration: {}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Location: !Ref PipelineArtifactsBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              RunOrder: 1
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Sub ${GitHubRepositoryOwner}
                Repo: !Sub ${GitHubRepositoryName}
                Branch: !Sub ${GitHubIntegrationBranch}
                OAuthToken: !Sub ${GitHubPersonalAccessToken}
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: LambdaToS3
              RunOrder: 2
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildLambdaToS3
              OutputArtifacts:
                - Name: BuildArtifact

  # S3 Bucket to hold artifacts for the Pipeline. Only requirement is that the S3 bucket has
  # versioning enabled. Other settings are following best practices for S3 buckets (encryption,
  # access logging, blocking public access)
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${RepositoryName}-pipeline
      AccessControl: LogDeliveryWrite
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - ServerSideEncryptionByDefault:
      #         SSEAlgorithm: aws:kms
      #         KMSMasterKeyID: alias/aws/s3
      LoggingConfiguration: {}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # Configures a webhook at GitHub to trigger the CodePipeline whenever a commit is pushed to the
  # integration branch configured for the stack
  PipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Name: !Sub ${GitHubRepositoryName}-pipeline-webhook-lambda
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Sub ${GitHubPersonalAccessToken}
      RegisterWithThirdParty: true
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Sub ${Pipeline}
      TargetAction: Source
      TargetPipelineVersion: !Sub ${Pipeline.Version}

  CodeBuildLambdaToS3:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${GitHubRepositoryName}-zip-lambda
      ServiceRole: !Sub ${CodeBuildRole.Arn}
      TimeoutInMinutes: 15
      Artifacts:
        Type: CODEPIPELINE
      SecondaryArtifacts:
        - Type: S3
          ArtifactIdentifier: appS3
          Packaging: ZIP
          Path: app
          Name: ms-logon.zip
          Location: !Ref LambdaBucket
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ImagePullCredentialsType: CODEBUILD
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ASPNETCORE_ENVIRONMENT
            Value: Production
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Source:
        Type: CODEPIPELINE
        BuildSpec: infra-lambda/buildspec.yml

  # CodeBuild project that is run any time a PR is created, updated, or reopened for the target
  # repository. The project will only run if the target branch of the PR is the same as the
  # integration branch
  CodeBuildPRProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${GitHubRepositoryName}-pull-requests-lambda
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_SOURCE_CACHE
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        ImagePullCredentialsType: CODEBUILD
        ComputeType: BUILD_GENERAL1_SMALL
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      ServiceRole: !Sub ${CodeBuildRole.Arn}
      Source:
        GitCloneDepth: 1
        Location: !Sub "https://github.com/${GitHubRepositoryOwner}/${GitHubRepositoryName}.git"
        ReportBuildStatus: true
        Type: GITHUB
      Triggers:
        Webhook: true
        # This Filter group ensures builds only run when a PR is created, updated, or reopened and the
        # target branch of the PR is the integration branch
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
              ExcludeMatchedPattern: false
            - Type: BASE_REF
              Pattern: !Sub ^refs/heads/${GitHubIntegrationBranch}$
              ExcludeMatchedPattern: false

  # This grants the CodeBuild service the ability to clone a repository as well as setup a webhook
  # NOTE: Only one of these tokens can be created per "ServerType" per region. If you plan on setting
  # up multiple pipelines within the same account and region, you may need to pull this particlar resource
  # into a different template
  CodeBuildCredentials:
    Condition: CreateCodeBuildCredentials
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      Token: !Sub ${GitHubPersonalAccessToken}
      ServerType: GITHUB
      AuthType: PERSONAL_ACCESS_TOKEN

  # IAM Role assumed by CodePipeline during pipeline executions. Gives permission to manage artifacts,
  # Call CodeBuild project and monitor status, and create and update CloudFormation stacks as part
  # of the deployment
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: GetAndPutArtifacts
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub ${PipelineArtifactsBucket.Arn}/*
              - Sid: ManageCodeBuildJob
                Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource:
                  - !Sub ${CodeBuildLambdaToS3.Arn}
              - Sid: CreateAndUpdateDeploymentStack
                Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeploymentStackName}/*
              - Sid: PassStackRoleToCloudFormation
                Effect: Allow
                Action: iam:PassRole
                Resource: !Sub ${CloudFormationStackRole.Arn}

  # Role that is passed to CloudFormation in order to deploy the production stack
  CloudFormationStackRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub ${CloudFormationStackPolicy}

  # Role assumed by CodeBuild projects. Permissions granted allow for logging to CloudWatch, managing artifacts,
  # validating CloudFormation templates, and the various permissions required to execute taskcat.
  # Note: The CloudFormation stack policy is also attached to this role, since the same permissions are required to
  # create/delete the test stacks through taskcat
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub ${CloudFormationStackPolicy}
        - !Sub ${TaskCatPolicy}
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LogToCloudWatch
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Sid: GetAndPutArtifacts
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub ${PipelineArtifactsBucket.Arn}/*
              - Sid: ValidateCloudFormationTemplate
                Effect: Allow
                Action: cloudformation:ValidateTemplate
                Resource: "*"

  # IAM Policy that determines what permissions CloudFormation has when deploying the production
  # stack. This policy defines the minimum permissions necessary to carry out deployments.
  # Note: Delete permissions are included here to account for deleting the stack
  CloudFormationStackPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: S3BucketPermissions
            Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:GetEncryptionConfiguration
              - s3:PutEncryptionConfiguration
              - s3:GetBucketAcl
              - s3:PutBucketAcl
              - s3:GetBucketLogging
              - s3:PutBucketLogging
            Resource: arn:aws:s3:::*
          - Sid: CloudFormationPermissions
            Effect: Allow
            Action:
              - iam:PassRole
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DeleteLogGroup
              - cloudwatch:DescribeAlarms
              - cloudwatch:DeleteAlarms
              - cloudwatch:DescribeAlarmsForMetric
              - cloudwatch:DisableAlarmActions
              - cloudwatch:EnableAlarmActions
              - cloudwatch:GetMetricData
              - cloudwatch:PutMetricAlarm
              - cloudwatch:PutMetricData
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: "*"

  # IAM Policy that grants permissions required for Taskcat execution.
  # Note: This policy doesn't include any permissions required to deploy the test stacks, these
  # permissions are required by the taskcat tool itself
  TaskCatPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: S3BucketPermissions
            Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:PutBucketPolicy
            Resource: arn:aws:s3:::taskcat-*
          - Sid: S3ObjectPermissions
            Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:GetObject
              - s3:PutObject
            Resource: arn:aws:s3:::taskcat-*/*
          - Sid: CloudFormationPermissions
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:DeleteStack
            Resource: !Sub arn:aws:cloudformation:*:${AWS::AccountId}:stack/tcat-*/*
          - Sid: ValidateCloudFormationTemplate
            Effect: Allow
            Action: cloudformation:ValidateTemplate
            Resource: "*"
